/* Package Manager Webview DOM */
(function () {
    window.PM = window.PM || {};

    window.PM.dom = {
        btnCreate: document.getElementById('btnCreate'),
        btnRefresh: document.getElementById('btnRefresh'),
        btnOpenCreate: document.getElementById('btnOpenCreate'),
        btnCloseCreate: document.getElementById('btnCloseCreate'),
        btnCancelCreate: document.getElementById('btnCancelCreate'),
        createModal: document.getElementById('createModal'),
        createBackdrop: document.getElementById('createBackdrop'),
        pkgNameInput: document.getElementById('pkgName'),
        pkgNameNormalizedHint: document.getElementById('pkgNameNormalizedHint'),
        buildTypeInput: document.getElementById('buildType'),
        licenseInput: document.getElementById('pkgLicense'),
        descriptionInput: document.getElementById('pkgDescription'),
        depsInput: document.getElementById('deps'),
        statusEl: document.getElementById('createStatus'),
        pkgStatusEl: document.getElementById('pkgStatus'),
        filterInput: document.getElementById('pkgFilter'),
        pkgCount: document.getElementById('pkgCount'),
        btnToggleWorkspacePackages: document.getElementById('btnToggleWorkspacePackages'),
        btnToggleOtherPackages: document.getElementById('btnToggleOtherPackages'),
        btnLoadOtherPackages: document.getElementById('btnLoadOtherPackages'),
        otherPkgList: document.getElementById('otherPkgList'),
        pinnedList: document.getElementById('pinnedList'),
        terminalList: document.getElementById('terminalList'),
        argsModal: document.getElementById('argsModal'),
        argsBackdrop: document.getElementById('argsBackdrop'),
        argsInput: document.getElementById('argsInput'),
        configName: document.getElementById('configName'),
        configList: document.getElementById('configList'),
        btnAddConfig: document.getElementById('btnAddConfig'),
        btnRemoveConfig: document.getElementById('btnRemoveConfig'),
        argsList: document.getElementById('argsList'),
        btnInsertAll: document.getElementById('btnInsertAll'),
        btnSaveArgs: document.getElementById('btnSaveArgs'),
        btnCancelArgs: document.getElementById('btnCancelArgs'),
        btnCloseArgs: document.getElementById('btnCloseArgs'),
        toggleBuildCheck: document.getElementById('toggleBuildCheck'),
        addNodeModal: document.getElementById('addNodeModal'),
        addNodeBackdrop: document.getElementById('addNodeBackdrop'),
        addNodePkg: document.getElementById('addNodePkg'),
        addNodeName: document.getElementById('addNodeName'),
        btnAddNode: document.getElementById('btnAddNode'),
        btnCancelAddNode: document.getElementById('btnCancelAddNode'),
        btnCloseAddNode: document.getElementById('btnCloseAddNode'),
        addNodeStatus: document.getElementById('addNodeStatus'),
    };
})();
